image: node:6.6.0

before_script:
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

stages:
  - preparation
  - lint
  - deploy
  
install_dependencies:
  stage: preparation
  artifacts:
    untracked: true
  tags: 
    - node
  script:
    - npm i
  
lint_package:
  stage: lint
  dependencies:
    - install_dependencies
  tags:
    - node
  script:
    - npm run lint
      
upload_package:
  only:
    - master@jc3mp-packages/hashes
  image: registry.gitlab.nanos.io/jc3mp/gitlab-deploy:latest
  stage: deploy
  tags:
    - deploy
  script:
    - pack --exclude=node_modules *
    - upload packages
  artifacts:
    paths:
     - $CI_PROJECT_NAME.tar

cache:
  key: "$CI_BUILD_REF_NAME"
  untracked: true